// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA38oQynFi5xi_EJVKEjloZSp6izIDejzk',
    appId: '1:357613799041:web:f8f4e6668274b80db6af80',
    messagingSenderId: '357613799041',
    projectId: 'weatherapp-641dd',
    authDomain: 'weatherapp-641dd.firebaseapp.com',
    storageBucket: 'weatherapp-641dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyuw3OIsaFSBXCMtLp_7IJzDgtxgDLLGc',
    appId: '1:357613799041:android:5721de82b59cbacfb6af80',
    messagingSenderId: '357613799041',
    projectId: 'weatherapp-641dd',
    storageBucket: 'weatherapp-641dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM3S7pkILsnVJIdEXsrnGaj6Jq_x6LkG8',
    appId: '1:357613799041:ios:c5996df98fa0c7eab6af80',
    messagingSenderId: '357613799041',
    projectId: 'weatherapp-641dd',
    storageBucket: 'weatherapp-641dd.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM3S7pkILsnVJIdEXsrnGaj6Jq_x6LkG8',
    appId: '1:357613799041:ios:c5996df98fa0c7eab6af80',
    messagingSenderId: '357613799041',
    projectId: 'weatherapp-641dd',
    storageBucket: 'weatherapp-641dd.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA38oQynFi5xi_EJVKEjloZSp6izIDejzk',
    appId: '1:357613799041:web:0ab7dbf5212f7cfbb6af80',
    messagingSenderId: '357613799041',
    projectId: 'weatherapp-641dd',
    authDomain: 'weatherapp-641dd.firebaseapp.com',
    storageBucket: 'weatherapp-641dd.appspot.com',
  );
}
